### ISSUE TITLE
Hot reload error

### ISSUE THREAD

**Issue by Benbinbin** [yeqisong/crx3-dev-template#2]
when I modified the `App.vue` in `popup` folder and save it, then I encount the error

```sh
(node:3760) UnhandledPromiseRejectionWarning: Error: ENOTEMPTY: directory not empty, rmdir 'F:\Code\Web\Extension\crx3-dev-template\dist\libs'
    at Object.rmdirSync (fs.js:912:10)
    at emptyDir (F:\Code\Web\Extension\crx3-dev-template\node_modules\vite\dist\node\chunks\dep-1be34a63.js:4341:25)
    at prepareOutDir (F:\Code\Web\Extension\crx3-dev-template\node_modules\vite\dist\node\chunks\dep-1be34a63.js:51162:13)
    at WatchEmitter.<anonymous> (F:\Code\Web\Extension\crx3-dev-template\node_modules\vite\dist\node\chunks\dep-1be34a63.js:51113:25)
    at WatchEmitter.emit (events.js:400:28)
    at WatchEmitter.emit (domain.js:470:12)
    at Task.run (F:\Code\Web\Extension\crx3-dev-template\node_modules\rollup\dist\shared\watch.js:746:30)
    at Watcher.run (F:\Code\Web\Extension\crx3-dev-template\node_modules\rollup\dist\shared\watch.js:685:24)
    at Timeout._onTimeout (F:\Code\Web\Extension\crx3-dev-template\node_modules\rollup\dist\shared\watch.js:676:18)
    at listOnTimeout (internal/timers.js:557:17)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3760) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:3760) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by yeqisong** [comment]
window下”/"处理不当导致，已修复，请升级模板中的crx3到v1.0.7。
